language: ruby
cache: bundler
bundler_args: --without production

rvm:
 - 2.7.0
 
before_install:
 - gem install bundler:2.2.11

script:
 - bundle exec rspec
 
deploy:
 provider: heroku
 api_key: c396f8c7-9d5b-4ae5-8b16-bda33f067544
 app: blooming-hamlet-30711
 run: "rake db:migrate"
 on:
  all_branches: true